underlay-xy(
  underlay-xy(
    underlay-xy(
      circle(
        50, 
        "solid", 
        "lightgreen"), 
      30, 
      30, 
      circle(
        5, 
        "solid", 
        "red")), 
    60, 
    30, 
    circle(
      5, 
      "solid", 
      "red")),
  30,
  50,
  rectangle(40, 30, "outline", "black"))
